// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tsetsad_TMBExports
#include <TMB.hpp>
#include "aaa.hpp"
#include "mam.hpp"
#include "mmm.hpp"
#include "powermam.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "aaa") {
    return aaa(this);
  } else if(model == "mam") {
      return mam(this);
  } else if(model == "mmm") {
    return mmm(this);
  } else if (model == "powermam"){
    return powermam(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
